### ISSUE TITLE
Documentation reorganization (ja)

### ISSUE THREAD

**Issue by masaori335** [trafficserver-doc-ja/trafficserver-doc-ja#24]
English version of documentation is reorganized.
We need to support this.
Details in https://github.com/apache/trafficserver/pull/317

(Close https://github.com/trafficserver-doc-ja/trafficserver/issues/120)

**Comment by masaori335** [comment]
[Update doc-ja branch with upstream/master #121](https://github.com/trafficserver-doc-ja/trafficserver/pull/121) updated doc-ja branch of trafficserver-doc-ja/trafficserver.
See latest ja page! (http://trafficserver.readthedocs.org/ja/latest/) 
Thanks @hnakamur !

**Comment by hnakamur** [comment]
@masaori335 Thanks for your review and merging!
