### ISSUE TITLE
Salvage Obsolete Messages

### ISSUE THREAD

**Issue by masaori335** [trafficserver-doc-ja/trafficserver-doc-ja#27]
## 状況
- [Documentation reorganization (ja) #24](https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/issues/24) の対応前に msgid の変更により Obsolete Messages となっていたものがファイル名の変更等に伴い移行されなかったようです。
- 対象は [Fall 2014 Update PO files #22](https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/issues/22#issuecomment-63652867) の一覧の未対応のファイルに含まれていた Obsolete Messages と考えられます。
- Read The Docs のビルドログによるとこの変更前のコミットは [066ffe51e6e836cd23d8d90ec73ec05ffa53873a](https://github.com/trafficserver-doc-ja/trafficserver/commit/066ffe51e6e836cd23d8d90ec73ec05ffa53873a) のようです。

**Comment by masaori335** [comment]
対応する場合、Fall 2014 Update PO files #22 の未対応のファイルが Documentation reorganization でどのファイルに移行したかを探して、Obsolete Message を移していくんでしょうか？
何かいい方法があれば教えてください。
対応しない場合、二重に訳してしまう場合があります。ただ、そもそも msgid が変更になっているので訳し直す必要はいずれにしろあります。

**Comment by masaori335** [comment]
@maskit Any good idea?

**Comment by hnakamur** [comment]
私の方では https://github.com/hnakamur/gettext-go を改変して旧ファイルのObsolete Messagesのmsgidが新ファイルに一致する場合はコピーするように出来るか、今試行錯誤中です。
これが出来た場合も、ファジーマッチのような高度なことは出来ないので、msgidが変わっていた場合は手動で反映する必要は残ります。
旧ファイルのmsgidが新ファイルに一致するものがない一覧は出力できるので、それを元に作業可能かと思います。

**Comment by masaori335** [comment]
@hnakamur ありがとうございます。
> 私の方では https://github.com/hnakamur/gettext-go を改変して旧ファイルのObsolete Messagesのmsgidが新ファイルに一致する場合はコピーするように出来るか、今試行錯誤中です。
これが出来た場合も、ファジーマッチのような高度なことは出来ないので、msgidが変わっていた場合は手動で反映する必要は残ります。

もともと msgid が変更になったことによって `sphinx-intl update` した際に Obsolete Messages にされているので、多くのものが手動になりそうですね。マッチするものがあればいいんですが。

> 旧ファイルのmsgidが新ファイルに一致するものがない一覧は出力できるので、それを元に作業可能かと思います。

この一覧があると捗りそうですね！

**Comment by maskit** [comment]
移行できなかったメッセージの一覧は翻訳状況の回復に役立つと思います。
その一方で、翻訳が停滞していた間に追加された内容には、一度翻訳済みで現在は失われている内容より価値の高いものもあると思います。（どの部分に価値があると判断するかは読み手次第ですが。）

日本語ドキュメントの価値を高めることに注力すべきなので、移行できなかったメッセージについてはその一覧をスピードアップのための材料として活用するにとどめ、新しいPOファイルへの移植まではしなくてもよいと思います。
具体的な翻訳作業の流れとしては、翻訳者が必要性を感じたら一覧を grep するなどして対応するものを探すことになります。簡単なものであれば必ずしも探す必要はありません。これを必須としてしまうとむしろ作業効率が落ちる内容もあると思います。

もちろん移植による翻訳状況の回復もひとつの貢献方法だと思うので、それを止めるつもりはありませんが、サルベージ作業としては一覧の作成をゴールとするでよいと思います。

**Comment by hnakamur** [comment]
移行できなかったメッセージ一覧を作成しました。
[orphans.txt](https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/files/77075/orphans.txt)

[Update empty msgstr in dest dir with obsolete msgstr in src dir having the same msgid](https://gist.github.com/hnakamur/5eb07f0ec9932e385373)のPythonスクリプトを書いて上記の一覧を作成しました。
古いpoファイルのgitワークディレクトリと新しいpoファイルのgitワークディレクトリを用意しておいて、以下のコマンドで一覧を作成しました。

```
python3 -v venv
source venv/bin/activate
pip install pofile
python copyobsoletemsgstr.py orphans ${古いpoファイルのgitワークディレクトリ} ${新しいpoファイルのgitワークディレクトリ} > orphans.txt
cd  ${新しいpoファイルのgitワークディレクトリ} 
find . -name "*.po" -exec msgcat -w 78 -o {} {} \;
```

**Comment by masaori335** [comment]
@hnakamur 一覧ありがとうございます。

**Comment by masaori335** [comment]
自分も新しい PO ファイルへの移植まではやらなくていいと考えています。
『翻訳者や校正者が必要に応じてメッセージ一覧を参照する』ということで、この Issue はクローズします。

Reorganized されたドキュメントの翻訳を進めていきましょう。

**Comment by masaori335** [comment]
メモを Wiki に書きました。
https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/wiki#documentation-reorganization-2015

**Comment by hnakamur** [comment]
その後 [orphans.txt](https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/files/77075/orphans.txt) の翻訳文を再利用しつつ適宜変更して、いくつかプルリクエストを送っています。

再利用した翻訳文を消しこみした現時点の残りを共有します。
[orphans-2016-01-12.txt](https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/files/86060/orphans-2016-01-12.txt)

 [orphans.txt](https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/files/77075/orphans.txt) が1752 行に対して [orphans-2016-01-12.txt](https://github.com/trafficserver-doc-ja/trafficserver-doc-ja/files/86060/orphans-2016-01-12.txt) は 1488 行と 264 行減りました。
翻訳文 (msgstr) が空の行が 909 行あるので、実質の残りはその分少ないです。
